version: '2'
services:
      webserver:
        build:
             context: .
             dockerfile: Dockerfile
        container_name: tanah
        volumes:
          - .:/var/www/html
        links:
          - db
        ports:
          - 5003:80

      db:
        image: mariadb:latest
        container_name: tanahdb
        volumes:
          - ./data/mysql-data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=Suckhack24@
          - MYSQL_USER=suckhack24
          - MYSQL_PASSWORD=Suckhack24@
          - MYSQL_DATABASE=tanahdb
